### PR TITLE
[TASK] Add extension key for the site package

### PR DESCRIPTION
**Pull request by simonschaufi**

### CODE REVIEW

**Comment by oliverklee** [comment]
Why would this distribution have an extension key? It doesn't have `"type": "typo3-cms-extension"` in the `composer.json` and is not used as a TYPO3 extension. Am I missing something here?

**Comment by simonschaufi** [comment]
@oliverklee check which file was actually changed. It's not the root composer.json :smile: This package contains an extension.

**Comment by infabo** [comment]
LOL

Simon Schaufelberger ***@***.***> schrieb am Di., 27. Juli
2021, 23:46:

**Review by infabo — CHANGES_REQUESTED** [review]
You can safely remove the "replace" key too.

**Comment by oliverklee** [comment]
@simonschaufi Indeed, you're right! Totally missed that this was in the site package, not the distribution's `composer.json`.

To avoid this confusion, I propose updating the commit message and PR title to `[TASK] Add extension key for the site package`.

**Review by helhum — APPROVED** [review]

**Pull request merged**
